# Generated by Django 5.1.1 on 2024-10-24 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0003_businessservicecategory"),
        ("users", "0002_alter_user_first_name_alter_user_managed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaigninvite",
            name="actor",
        ),
        migrations.RemoveField(
            model_name="campaigninvite",
            name="candidate",
        ),
        migrations.RemoveField(
            model_name="campaigninvite",
            name="to_user",
        ),
        migrations.RemoveField(
            model_name="race",
            name="government_level",
        ),
        migrations.RemoveField(
            model_name="user",
            name="government_level",
        ),
        migrations.RemoveField(
            model_name="user",
            name="race",
        ),
        migrations.DeleteModel(
            name="BlockWalker",
        ),
        migrations.DeleteModel(
            name="CampaignManager",
        ),
        migrations.DeleteModel(
            name="Candidate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="campaign_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="campaign_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="candidate_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="current_team",
        ),
        migrations.RemoveField(
            model_name="user",
            name="enabled_2fa",
        ),
        migrations.RemoveField(
            model_name="user",
            name="government_level_title",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hours_available_per_week",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_approve_to_export_data",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_have_contact_support_status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_have_subscription",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_position_data_have_more_one_county",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_send_mail_approve_demo_account",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_show_create_blockwalk_popup",
        ),
        migrations.RemoveField(
            model_name="user",
            name="managed_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="notification",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="position_value_mapping",
        ),
        migrations.RemoveField(
            model_name="user",
            name="previous_position_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="race_jurisdiction_request",
        ),
        migrations.RemoveField(
            model_name="user",
            name="race_title",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="business_address",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_fullname",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_phone_country_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_phone_e164",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="region_served",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="service_category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="systems.businessservicecategory"
            ),
        ),
        migrations.DeleteModel(
            name="CampaignInvite",
        ),
        migrations.DeleteModel(
            name="GovernmentLevel",
        ),
        migrations.DeleteModel(
            name="Race",
        ),
    ]
