# Generated by Django 5.1.1 on 2025-03-03 03:36

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_admin_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255, unique=True, verbose_name='Business Name')),
                ('business_address', models.CharField(max_length=500, verbose_name='Business Address')),
                ('region_served', models.JSONField(default=dict, verbose_name='Region Served')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Additional Information')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region_served',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.company'),
        ),
    ]
