# Generated by Django 5.1.1 on 2025-03-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_remove_user_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dashboard_data_uri',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
