# Generated by Django 5.1.1 on 2025-03-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_company_dashboard_data_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sales Representative', 'Sales Representative'), ('Regular User', 'Regular User')], default='Regular User', max_length=30),
        ),
    ]
