# Generated by Django 5.1.1 on 2025-03-04 09:54

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[],
            options={
                "verbose_name_plural": "Admins",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ApproveUser",
            fields=[],
            options={
                "verbose_name_plural": "Approved Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PendingUser",
            fields=[],
            options={
                "verbose_name_plural": "Pending Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="RegularUser",
            fields=[],
            options={
                "verbose_name_plural": "Regular Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SalesRepresentative",
            fields=[],
            options={
                "verbose_name_plural": "Sales Representatives",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Approved", "Approved"), ("Rejected", "Rejected")],
                default="Pending",
                help_text="User approval status",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_via",
            field=models.CharField(
                choices=[("admin", "admin"), ("web", "web"), ("mobile", "mobile")], default="web", max_length=10
            ),
        ),
    ]
