# Generated by Django 5.1.1 on 2025-03-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_admin_approveuser_pendinguser_regularuser_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="contact_fullname",
            new_name="contact_firstname",
        ),
        migrations.AddField(
            model_name="user",
            name="contact_lastname",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
