# Generated by Django 5.1.1 on 2025-03-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_contact_fullname_user_contact_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="business_address",
            field=models.JSONField(default=dict, verbose_name="Business Address"),
        ),
    ]
