# Generated by Django 5.1.1 on 2025-03-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_company_business_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="contact_firstname",
        ),
        migrations.RemoveField(
            model_name="user",
            name="contact_lastname",
        ),
        migrations.RemoveField(
            model_name="user",
            name="contact_phone_country_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="contact_phone_e164",
        ),
        migrations.RemoveField(
            model_name="user",
            name="contact_phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="dashboard_data_uri",
        ),
        migrations.AddField(
            model_name="company",
            name="contact_firstname",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_lastname",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_phone_country_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_phone_e164",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
