# Generated by Django 5.1.1 on 2025-03-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_user_contact_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="centre_point",
            field=models.JSONField(blank=True, null=True, verbose_name="Centre Point"),
        ),
    ]
