# Generated by Django 5.1.1 on 2025-03-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_user_contact_firstname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_approved",
        ),
    ]
