# Generated by Django 5.1.1 on 2025-03-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_company_centre_point"),
        ("users", "0012_remove_user_is_approved"),
    ]

    operations = []
