# Generated by Django 5.1.1 on 2025-03-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_merge_20250312_1151"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification",
            field=models.BooleanField(default=True),
        ),
    ]
