# Generated by Django 5.1.1 on 2025-03-26 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("lead_id", models.CharField(max_length=50)),
                ("event", models.CharField(max_length=100)),
                ("detail", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Log",
                "verbose_name_plural": "Sale Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
