# Generated by Django 5.1.1 on 2025-03-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_salelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="region_served",
            field=models.JSONField(default=list, verbose_name="Region Served"),
        ),
    ]
