# Generated by Django 5.1.1 on 2025-03-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_company_region_served"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salelog",
            name="lead_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
