# Generated by Django 5.1.1 on 2025-04-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_salelog_lead_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_csv_processing",
            field=models.BooleanField(default=False, verbose_name="CSV Processing Status"),
        ),
    ]
