# Generated by Django 5.1.1 on 2025-04-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_company_is_csv_processing"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="last_update_csv_time",
            field=models.DateTimeField(auto_now=True, verbose_name="Last CSV Update Time"),
        ),
    ]
