# Generated by Django 5.1.1 on 2025-04-15 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_created_user_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_systemuser',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a system user with special permissions.', verbose_name='System User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sales Representative', 'Sales Representative'), ('Regular User', 'Regular User')], default='Regular User', max_length=30, verbose_name='Role'),
        ),
    ]
