LEARN_MORE_WEB = "Learn more - Web"
TERMS_OF_SERVICE_WEB = "Terms of Service - Web"
TERMS_OF_SERVICE_MOBILE = "Terms of Service - Mobile"
PRIVACY_POLICY_WEB = "Privacy Policy - Web"
PRIVACY_POLICY_MOBILE = "Privacy Policy - Mobile"
COPYRIGHT_WEB = "Copyright - Web"
SUPPORT_STATUS_CONSTANTS = "Support Status"
CONTENT_TALK_CONSTANT_VISIT = "Contact Visit"
CONTENT_TALK_CONSTANT_CALL_TEXT = "Contact Call Text"
CONTENT_TALK_CONSTANT_MAIL = "Contact Mail"
CONTENT_TALK_CONSTANT_DIGITAL = "Contact Digital"

PAGE_CHOICES = [
    (LEARN_MORE_WEB, LEARN_MORE_WEB),
    (TERMS_OF_SERVICE_MOBILE, TERMS_OF_SERVICE_MOBILE),
    (TERMS_OF_SERVICE_WEB, TERMS_OF_SERVICE_WEB),
    (PRIVACY_POLICY_WEB, PRIVACY_POLICY_WEB),
    (PRIVACY_POLICY_MOBILE, PRIVACY_POLICY_MOBILE),
]


CONTENT_TALK_CHOICES = [
    (CONTENT_TALK_CONSTANT_VISIT, CONTENT_TALK_CONSTANT_VISIT),
    (CONTENT_TALK_CONSTANT_MAIL, CONTENT_TALK_CONSTANT_MAIL),
    (CONTENT_TALK_CONSTANT_DIGITAL, CONTENT_TALK_CONSTANT_DIGITAL),
    (CONTENT_TALK_CONSTANT_CALL_TEXT, CONTENT_TALK_CONSTANT_CALL_TEXT),
]

STORM_DAMAGE_TIME_UNIT = [
    ("years", "years"),
    ("months", "months"),
    ("weeks", "weeks"),
    ("days", "days"),
]
