version: '3'

services:

  api:
    restart: always
    build:
      context: .
      dockerfile: containers/django/Dockerfile-dev
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    command: /usr/src/api/.start-dev.sh
    ports:
      - '8000:8000'
      - '9000:22'
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.${ENVIRONMENT}
    env_file:
      - ./containers/.envs/.${ENVIRONMENT}/.postgres
      - api/config/settings/.env
    volumes:
      - .:/usr/src/app
    links:
      - redis
      - postgres

  redis:
    image: redis:latest
    restart: always

  postgres:
    restart: always
    build:
      context: containers/postgres
      dockerfile: Dockerfile
    volumes:
      - ./containers/data/postgres:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - ./containers/.envs/.${ENVIRONMENT}/.postgres

  #mysql:
  #  build:
  #    context: .
  #    dockerfile: containers/mysql/Dockerfile
  #  restart: always
  #  environment:
  #    MYSQL_DATABASE: 'db'
  #    # So you don't have to use root, but you can if you like
  #    MYSQL_USER: 'root'
  #    # You can use whatever password you like
  #    MYSQL_PASSWORD: 'root'
  #    # Password for root access
  #    MYSQL_ROOT_PASSWORD: 'root'
  #  ports:
  #    # <Port exposed> : < MySQL Port running inside container>
  #    - '3306:3306'
  #  expose:
  #    # Opens port 3306 on the container
  #    - '3306'
  #    # Where our data will be persisted
  #  volumes:
  #    - ./containers/data/mysql:/var/lib/mysql

  #grafana:
  #  image: grafana/grafana:latest
  #  restart: always
  #  ports:
  #    - "3000:3000"
  #  env_file:
  #    - 'containers/grafana/.env.grafana'
  #  volumes:
  #    # Data persistency
  #    - ./containers/data/grafana:/var/lib/grafana

  #prometheus:
  #  image: prom/prometheus
  #  restart: always
  #  ports:
  #    - 9090:9090
  #  volumes:
  #    - ./containers/data/prometheus:/var/lib/prometheus
