# Generated by Django 2.2.7 on 2022-02-24 03:23

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("minimal_version", models.CharField(default="1.0.0", max_length=10)),
                ("current_version", models.CharField(default="1.0.0", max_length=10)),
                (
                    "platform",
                    models.CharField(
                        blank=True, choices=[("IOS", "iOS"), ("DROID", "Android")], max_length=20, null=True
                    ),
                ),
                ("app_store_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "App Version",
                "verbose_name_plural": "App Versions",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("message", models.CharField(blank=True, max_length=250, null=True)),
                ("icon", models.CharField(blank=True, max_length=250, null=True)),
                ("background", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("UPDATE_APP", "UPDATE_APP")],
                        default="UPDATE_APP",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
    ]
