MESSAGE_STATUS_QUEUED = "QUEUED"
MESSAGE_STATUS_SENT = "SENT"
MESSAGE_STATUS_FAILED = "FAILED"
MESSAGE_STATUS_CANCELLED = "CANCELLED"
MESSAGE_STATUS_SKIPPED = "SKIPPED"

MESSAGE_STATUS_CHOICES = [
    (MESSAGE_STATUS_QUEUED, MESSAGE_STATUS_QUEUED),
    (MESSAGE_STATUS_SENT, MESSAGE_STATUS_SENT),
    (MESSAGE_STATUS_FAILED, MESSAGE_STATUS_FAILED),
    (MESSAGE_STATUS_CANCELLED, MESSAGE_STATUS_CANCELLED),
    (MESSAGE_STATUS_SKIPPED, MESSAGE_STATUS_SKIPPED),
]


PROVIDER_ARRIVE = "1"
PROVIDER_APPOINTMENT_SCHEDULED = "2"
CUSTOMER_APPOINTMENT_SCHEDULED = "3"
CUSTOMER_UPDATE_APPOINTMENT_DATETIME = "4"
PROVIDER_ORDER_CANCELLED = "5"
PROVIDER_RECEIVE_TIP = "6"
PROVIDER_COMPLETE_FINAL_PAYMENT = "7"
CUSTOMER_UPDATE_ORDER = "8"
SHIPPING_SILENT_PUSH = "9"
PROVIDER_START_SHIPPING_ORDER = "10"
PROVIDER_FINISH_ORDER = "11"
PROVIDER_ORDER_COMPLETE = "12"
PATIENT_SUBMIT_RATE = "13"
PROVIDER_CANCELLED_ORDER = "14"
CHAT_MESSAGE = "15"
REFUND_TRANSACTION = "16"
CUSTOMER_CANCEL_ORDER_TO_PATIENT = "17"
ORDER_STATUS_SILENT_PUSH = "18"
PROVIDER_REMIND_SHIPPING = "19"
HAS_ARRIVED_SILENT_PUSH = "20"
PROVIDER_REMIND_SHIPPING_SILENT_PUSH = "21"
CUSTOMER_AUTO_CANCEL_ORDER_TO_PATIENT = CUSTOMER_CANCEL_ORDER_TO_PATIENT

NOTIFICATION_TYPE = [
    (PROVIDER_ARRIVE, PROVIDER_ARRIVE),
    (PROVIDER_APPOINTMENT_SCHEDULED, PROVIDER_APPOINTMENT_SCHEDULED),
    (CUSTOMER_APPOINTMENT_SCHEDULED, CUSTOMER_APPOINTMENT_SCHEDULED),
    (CUSTOMER_UPDATE_APPOINTMENT_DATETIME, CUSTOMER_UPDATE_APPOINTMENT_DATETIME),
    (PROVIDER_ORDER_CANCELLED, PROVIDER_ORDER_CANCELLED),
    (PROVIDER_RECEIVE_TIP, PROVIDER_RECEIVE_TIP),
    (CUSTOMER_UPDATE_ORDER, CUSTOMER_UPDATE_ORDER),
    (SHIPPING_SILENT_PUSH, SHIPPING_SILENT_PUSH),
    (PROVIDER_START_SHIPPING_ORDER, PROVIDER_START_SHIPPING_ORDER),
    (PROVIDER_FINISH_ORDER, PROVIDER_FINISH_ORDER),
    (PROVIDER_ORDER_COMPLETE, PROVIDER_ORDER_COMPLETE),
    (PATIENT_SUBMIT_RATE, PATIENT_SUBMIT_RATE),
    (PROVIDER_CANCELLED_ORDER, PROVIDER_CANCELLED_ORDER),
    (REFUND_TRANSACTION, REFUND_TRANSACTION),
    (CUSTOMER_CANCEL_ORDER_TO_PATIENT, CUSTOMER_CANCEL_ORDER_TO_PATIENT),
    (ORDER_STATUS_SILENT_PUSH, ORDER_STATUS_SILENT_PUSH),
    (PROVIDER_REMIND_SHIPPING, PROVIDER_REMIND_SHIPPING),
    (HAS_ARRIVED_SILENT_PUSH, HAS_ARRIVED_SILENT_PUSH),
    (PROVIDER_REMIND_SHIPPING_SILENT_PUSH, PROVIDER_REMIND_SHIPPING_SILENT_PUSH),
]
