# Generated by Django 5.1.1 on 2025-03-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="USLocationInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("state_abbr", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("zipcode_type", models.CharField(blank=True, max_length=255, null=True)),
                ("county", models.CharField(blank=True, max_length=255, null=True)),
                ("zipcode", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "US Location Info",
                "verbose_name_plural": "US Location Info",
                "indexes": [
                    models.Index(fields=["state"], name="location_us_state_74070b_idx"),
                    models.Index(fields=["city"], name="location_us_city_7d7d54_idx"),
                    models.Index(fields=["zipcode"], name="location_us_zipcode_4c5fcc_idx"),
                ],
            },
        ),
    ]
