# Generated by Django 5.1.1 on 2024-09-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20220224_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='thumbnail_path',
            field=models.JSONField(null=True),
        ),
    ]
