# Generated by Django 5.1.1 on 2025-03-04 02:25

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceInfo",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("device_id", models.CharField(max_length=255, unique=True)),
                (
                    "platform",
                    models.CharField(
                        blank=True, choices=[("IOS", "iOS"), ("DROID", "Android")], max_length=20, null=True
                    ),
                ),
                ("platform_version", models.CharField(blank=True, max_length=10, null=True)),
                ("blocked", models.BooleanField(default=False)),
                ("app_version", models.CharField(blank=True, max_length=10, null=True)),
                ("memo", models.CharField(blank=True, help_text="Internal notes", max_length=250, null=True)),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("in_use", models.BooleanField(default=True)),
                ("memo", models.CharField(blank=True, help_text="Internal notes", max_length=250, null=True)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="devices.deviceinfo")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "User - Device",
                "verbose_name_plural": "User - Device(s)",
                "unique_together": {("device", "user")},
            },
        ),
    ]
