# Generated by Django 5.1.1 on 2024-10-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("export_building_permit_count_limit", models.BigIntegerField(default=10000000)),
            ],
        ),
    ]
