# Generated by Django 5.1.1 on 2024-10-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='import_chunk_size',
            field=models.IntegerField(default=100000),
        ),
    ]
