# Generated by Django 5.1.1 on 2025-03-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0003_businessservicecategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="HirePredictionConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HomeSizeConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=30)),
                ("total_sqft_from", models.IntegerField(blank=True, null=True)),
                ("total_sqft_to", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotInterestedReasonConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RoofMaterialConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SaleStatusConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StormDamageConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=100)),
                ("value", models.IntegerField(blank=True, null=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[("years", "years"), ("months", "months"), ("weeks", "weeks"), ("days", "days")],
                        default="",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BusinessServiceCategory",
        ),
        migrations.DeleteModel(
            name="ContentTalkConfig",
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="customer_lead_import_limit",
            field=models.BigIntegerField(default=10000, help_text="Maximum number of leads a customer can import."),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="customer_max_lead_file_size",
            field=models.BigIntegerField(
                default=10000, help_text="Maximum file size (in bytes) for lead import by a customer."
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="lead_update_allowed_distance",
            field=models.IntegerField(
                default=10, help_text="Maximum distance (in km/miles) allowed for updating a lead."
            ),
        ),
    ]
