# Generated by Django 5.1.1 on 2025-03-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0005_hirepredictionconfig_key_hirepredictionconfig_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="facebook_page_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="instagram_page_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="x_page_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
