# Generated by Django 5.1.1 on 2025-03-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0007_homesizeconfig_value_stormdamageconfig_unit_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stormdamageconfig",
            name="unit_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stormdamageconfig",
            name="value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
