# Generated by Django 5.1.1 on 2025-03-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0009_hirepredictionconfig_hex_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="csv_map_generation_duration",
            field=models.BigIntegerField(
                default=1800, help_text="Time duration (in seconds) for generating a lead CSV file"
            ),
        ),
    ]
