# Generated by Django 5.1.1 on 2025-03-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0003_systemconfig_import_chunk_size"),
        ("systems", "0010_systemconfig_csv_map_generation_duration"),
    ]

    operations = []
