# Generated by Django 5.1.1 on 2025-03-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0011_merge_20250319_1747"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="email_footer_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
