# Generated by Django 5.1.1 on 2025-03-24 03:31

import s3direct.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0012_systemconfig_email_footer_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="csv_example_file",
            field=s3direct.fields.S3DirectField(
                blank=True, help_text="file name allowed character is a-z, 1-9", null=True
            ),
        ),
    ]
