# Generated by Django 5.1.1 on 2025-03-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0013_systemconfig_csv_example_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="visit_valid_distance",
            field=models.IntegerField(
                default=100, help_text="Maximum distance (in feet) allowed for validating a visit."
            ),
        ),
    ]
