# Generated by Django 5.1.1 on 2025-03-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0014_systemconfig_visit_valid_distance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemconfig",
            name="lead_update_allowed_distance",
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="reach_valid_distance",
            field=models.IntegerField(
                default=10, help_text="Maximum distance (in feet) allowed for validating a reach."
            ),
        ),
    ]
