# Generated by Django 5.1.1 on 2025-04-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0016_hirepredictionconfig_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notinterestedreasonconfig',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
