# Generated by Django 5.1.1 on 2025-04-14 03:59

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0017_notinterestedreasonconfig_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
