# Generated by Django 5.1.1 on 2025-03-25 10:59

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("verb", models.CharField(max_length=100)),
                ("topic", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("content", models.CharField(blank=True, max_length=250, null=True)),
                ("template", models.CharField(blank=True, help_text="Message template", max_length=250, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("QUEUED", "QUEUED"),
                            ("SENT", "SENT"),
                            ("FAILED", "FAILED"),
                            ("CANCELLED", "CANCELLED"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        default="QUEUED",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("payload", models.JSONField(blank=True, null=True)),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                ("read", models.BooleanField(default=False)),
                ("visible", models.BooleanField(default=True, help_text="Visible to user?")),
                ("memo", models.CharField(blank=True, help_text="Internal Notes", max_length=250, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "indexes": [
                    models.Index(fields=["user"], name="notificatio_user_id_2120fc_idx"),
                    models.Index(fields=["created"], name="notificatio_created_f8e0c1_idx"),
                    models.Index(fields=["user", "visible", "is_removed"], name="notificatio_user_id_1606bc_idx"),
                ],
            },
        ),
    ]
